from sys import argv

script, filename = argv

print "We're going to erase %r." % filename
print "If you don't want that, hit CTRL-C (^C)."
print "If you do want that, hit RETURN."

raw_input("?")

print "Opening the file..."
#open the file and truncate it to length zero or create text file for writing
target = open(filename, 'w')

print "Truncating the file. Goodbye!"
#delete content of file, leaves you with an empty file that can be edited
target.truncate()

print "Now I'm going to ask you for three lines.\n"

line1 = raw_input("line 1: ")
line2 = raw_input("line 2: ")
line3 = raw_input("line 3: ")

print "\nI'm going to write these to the file."

#write lines into file and start a new line for each sentence
'''target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
target.write("\n")'''

#summarizes the lines that were generated by raw_input from the user into one variable and spaces it out evely
lines = "%s \n%s \n%s" % (line1, line2, line3)

#write the new variable lines into the document target, replaces the lines 28-33
target.write(lines)

print "And finally we read and close it.\n"

#close target
target.close()

#redefine target as the opened new edited file
target = open(filename)
#read and print
print target.read()
#close
target.close()

'''important commands
close -- closes the file, like file->save in your editor
read -- reads the contents of the file. Can assign result to a variable
readline -- reads just one line of a text
truncate -- empties the file
write('stuff') -- writes "stuff" into the file'''

'''modes for open()
'w' -- open file in 'write mode'
'r' -- read
'a' -- append'''